name             'joomla'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures joomla'
long_description 'Installs/Configures joomla'
version          '0.1.0'
