# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrantfile drives the dev environment for the joomla cookbook
# 
# Create the following sites: admin site, n other sites
# Templates:
# - admin (control over other sites)
# - blank (empty site as if you had just run the Joomla installer)
# - marketing starter template (from joomla-template project)

# ----------------------------------------------------------------------------
# Things that might need tweaking for your computer
# ----------------------------------------------------------------------------

DOMAIN = 'joomla.local'
HOSTNAME = 'dev'
FQDN = "#{HOSTNAME}.#{DOMAIN}"
SUBNET = '192.168.8'
DEBUG = false   # Set to true for verbose output
# On our local (host) machine, we will be able to see and edit the files that
# are used by the guest (virtual) machine.
LOCAL_DOCROOT = '~/www'
DOCROOT = '/var/www'

MEMORY = 2048

# ----------------------------------------------------------------------------

Vagrant.require_version '>= 1.5.0'

Vagrant.configure('2') do |config|

# Configure vagrant plugins
  config.cache.auto_detect = true if Vagrant.has_plugin?('vagrant-cachier')
  config.omnibus.chef_version = 'latest' if Vagrant.has_plugin?('vagrant-omnibus')
  config.berkshelf.enabled = true

  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true
  end

  config.vm.hostname = FQDN
  config.hostmanager.aliases = %W( admin.#{DOMAIN} empty.#{DOMAIN} ) if Vagrant.has_plugin?('vagrant-hostmanager')

  config.vm.box = 'bento/ubuntu-14.04'
  config.vm.box_check_update = false

  config.vm.network :private_network, ip: "#{SUBNET}.11"
  config.vm.synced_folder LOCAL_DOCROOT, DOCROOT, create: true,
    owner: "vagrant",
    group: "www-data",
    mount_options: ["dmode=775,fmode=664"]

  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
    vb.customize ["modifyvm", :id, "--memory", MEMORY]
  end

  # Patch ubuntu "stdin: is not a tty" error
  config.vm.provision 'shell', inline: "sudo sed -i \'s/^mesg n$/tty -s \\&\\& mesg n/g\' /root/.profile"

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug if DEBUG
    chef.verbose_logging = DEBUG
    chef.json = {
      joomla: {
        domain: "#{DOMAIN}"
      },
      mysql: {
        server_root_password: 'rootpass',
        server_debian_password: 'debpass',
        server_repl_password: 'replpass'
      }
    }

    chef.run_list = [
      'recipe[joomla::default]'
    ]
  end
end
