# -*- mode: ruby -*-
# vi: set ft=ruby :

# ----------------------------------------------------------------------------
# Things that might need tweaking for your computer
# ----------------------------------------------------------------------------

DOMAIN = 'joomla.local'
HOSTNAME = 'dev'
FQDN = "#{HOSTNAME}.#{DOMAIN}"
SUBNET = '192.168.8'
DEBUG = false   # Set to true for verbose output

MEMORY = 2048

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.cache.auto_detect = true if Vagrant.has_plugin?('vagrant-cachier')
  config.omnibus.chef_version = 'latest' if Vagrant.has_plugin?('vagrant-omnibus')
  config.berkshelf.enabled = true

  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.include_offline = true
  end

  config.vm.hostname = FQDN
  config.hostmanager.aliases = %W(#{HOSTNAME}) if Vagrant.has_plugin?('vagrant-hostmanager')

  config.vm.box = 'bento/ubuntu-14.04'

  config.vm.network :private_network, ip: "#{SUBNET}.11"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY]
  end

  # The path to the Berksfile to use with Vagrant Berkshelf
  # config.berkshelf.berksfile_path = "./Berksfile"

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug if DEBUG
    chef.verbose_logging = DEBUG
    chef.json = {
      joomla: {
        domain: "#{DOMAIN}"
      },
      mysql: {
        server_root_password: 'rootpass',
        server_debian_password: 'debpass',
        server_repl_password: 'replpass'
      }
    }

    chef.run_list = [
      'recipe[joomla::default]'
    ]
  end
end
